services:
  redpanda:
    image: redpandadata/redpanda:v24.1.8
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp=1
      - --memory=1G
      - --reserve-memory=0M
      - --node-id=0
      - --check=false
      - --kafka-addr=PLAINTEXT://0.0.0.0:9092
      - --advertise-kafka-addr=PLAINTEXT://redpanda:9092
    ports:
      - "9092:9092"
      - "9644:9644"

  redpanda-console:
    image: redpandadata/console:latest
    ports:
      - "8080:8080"
    environment:
      KAFKA_BROKERS: redpanda:9092
    depends_on:
      - redpanda

  redis:
    image: redis:7
    ports:
      - "6379:6379"

  spark:
    image: apache/spark:3.5.8-scala2.12-java17-python3-r-ubuntu
    depends_on:
      - redpanda
    volumes:
      - ./spark/jobs:/opt/spark/jobs
      - ./spark/checkpoints:/opt/spark/checkpoints
      - ./spark/lake:/opt/spark/lake
    environment:
      HOME: /tmp
      SPARK_LOCAL_DIRS: /tmp/spark-local
      SPARK_SUBMIT_OPTS: -Duser.home=/tmp -Divy.home=/tmp/.ivy2 -Divy.cache.dir=/tmp/.ivy2/cache
    command: >
      /opt/spark/bin/spark-shell
      --packages org.apache.spark:spark-sql-kafka-0-10_2.12:3.5.8
      --conf spark.sql.streaming.checkpointLocation=/opt/spark/checkpoints
      -i /opt/spark/jobs/rover-stream.scala

  rover-emulator:
    build:
      context: ./src
      dockerfile: RoverEmulator/Dockerfile
    environment:
      Kafka__BootstrapServers: redpanda:9092
      Simulation__OriginLat: 52.2297
      Simulation__OriginLon: 21.0122
      Simulation__InitialRoverCount: 8
    depends_on:
      - redpanda

  dashboard:
    build:
      context: ./src
      dockerfile: FleetDashboard/Dockerfile
    environment:
      Redis__Configuration: redis:6379
    ports:
      - "8088:8080"
    depends_on:
      - redis
